### ISSUE TITLE
Option "-a"

### ISSUE THREAD

**Issue by staeglis** [perlancar/perl-App-rsync-retry#1]
Hi,

I tried to use rsync-retry with the rsync option "-a". I'm not an perl programmer, but it seems that rsync-retry is using "-a" as short-cut for "--retry-all":
'retry-on-all|a' => \$Opts{retry_on_all},``

That's a problem, because an option shouldn't be defined twice (by the program and by the wrapper). This isn't the documented behavior either. But it seems that "-a" won't be passed to rsync.

Best,
Stefan

**Comment by perlancar** [comment]
You're right, I don't know what I was thinking. I use rsync -a all the time. Removed the shortcut and released 0.006. Thanks!
